--------------------------------------------------------------------------------
--  Handler.......... : onEnterFrame
--  Author........... : 
--  Description...... : 
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
function AI_ENVIRONMENT.onEnterFrame (  )
--------------------------------------------------------------------------------
	
--     local nTime = application.getAverageFrameTime ( )
--     
--     --------------------- DECREMENTATION DU TIMER --------------------------------------
--     
--     if ( this.bButterfly ( ) )
--     then
--         this.nButterflyTime ( this.nButterflyTime (  ) - nTime )
--         if( this.nButterflyTime ( ) < 1 )
--         then
--             this.sendEvent ( "onLaunchButterfly" )
--             this.SetTimer ( "Butterfly" )
--         end
--     end
--     
--     if ( this.bPterodactyl ( ) )
--     then
--         this.nPterodactylTime ( this.nPterodactylTime (  ) - nTime )
--         if( this.nPterodactylTime ( ) < 1 )
--         then
--             this.sendEvent ( "onLaunchPterodactyl" )
--             this.SetTimer ( "Pterodactyl" )
--         end
--     end
--     
--     if ( this.bWind ( ) )
--     then
--         this.nWindTimer ( this.nWindTimer ( ) - nTime )
--         if( this.nWindTimer ( ) < 1 )
--         then
--             this.sendEvent ( "onLaunchWind" )
--             this.SetTimer ( "Wind" )
--         end
--     end
--     
--     if ( this.bLava ( ) )
--     then
--         this.nLavaTimer ( this.nLavaTimer ( ) - nTime )
--         if( this.nLavaTimer ( ) < 0.5 )
--         then
--             this.sendEvent ( "onLaunchLava" )
--             this.SetTimer ( "Lava" )
--         end
--     end
    
--------------------------------------------------------------------------------
end
--------------------------------------------------------------------------------
